### ISSUE TITLE
AVleak source code?

### ISSUE THREAD

**Issue by LusKrew** [0xAlexei/Publications#1]
Hey man, great job on the AVleak tool, read your paper and watched your presentation, but in the paper you said you will share the code soon, but i couldn't find it in your github, where can i find it?

**Comment by 0xAlexei** [comment]
Thanks! 

I don't recall saying we'd share the code, and we never did, and will not be.

In any case, there's been at least one open source implementation of the ideas in the paper, but I can't vouch for it, I've never run it: https://github.com/calebcheng00/AVAudit
